//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { departmentsEntity } from './db/departments.entity';
import { initiativesEntity } from './db/initiatives.entity';
import { goalsEntity } from './db/goals.entity';
import { emissionSourcesEntity } from './db/emissionSources.entity';
import { resourceUsageEntity } from './db/resourceUsage.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      departmentsEntity,
      initiativesEntity,
      goalsEntity,
      emissionSourcesEntity,
      resourceUsageEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        {
          userName: 'userName 1',
          department: 1,
          password: 'password 1',
          email: 'email 1',
          id: 70,
        },
        {
          userName: 'userName 2',
          department: 2,
          password: 'password 2',
          email: 'email 2',
          id: 62,
        },
        {
          userName: 'userName 3',
          department: 3,
          password: 'password 3',
          email: 'email 3',
          id: 84,
        },
        {
          userName: 'userName 4',
          department: 4,
          password: 'password 4',
          email: 'email 4',
          id: 66,
        },
        {
          userName: 'userName 5',
          department: 5,
          password: 'password 5',
          email: 'email 5',
          id: 13,
        },
      ],
      departments: [
        { departmentName: 'departmentName 1', departmentHead: 1, id: 70 },
        { departmentName: 'departmentName 2', departmentHead: 2, id: 57 },
        { departmentName: 'departmentName 3', departmentHead: 3, id: 44 },
        { departmentName: 'departmentName 4', departmentHead: 4, id: 96 },
        { departmentName: 'departmentName 5', departmentHead: 5, id: 33 },
      ],
      initiatives: [
        {
          name: 'name 1',
          description: 'description 1',
          startDate: '2024-04-23T14:56:14.278Z',
          endDate: '2024-04-15T14:17:51.446Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 43,
        },
        {
          name: 'name 2',
          description: 'description 2',
          startDate: '2024-03-25T12:44:09.488Z',
          endDate: '2024-10-27T11:00:32.976Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 19,
        },
        {
          name: 'name 3',
          description: 'description 3',
          startDate: '2025-01-15T15:52:48.733Z',
          endDate: '2023-12-12T03:37:38.212Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 90,
        },
        {
          name: 'name 4',
          description: 'description 4',
          startDate: '2024-05-19T21:25:23.094Z',
          endDate: '2025-03-28T23:34:44.165Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 92,
        },
        {
          name: 'name 5',
          description: 'description 5',
          startDate: '2024-04-24T14:06:40.108Z',
          endDate: '2024-05-25T12:40:35.020Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 5,
        },
      ],
      goals: [
        {
          name: 'name 1',
          description: 'description 1',
          targetDate: '2024-03-24T20:28:14.569Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 96,
        },
        {
          name: 'name 2',
          description: 'description 2',
          targetDate: '2024-08-27T14:20:39.531Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 60,
        },
        {
          name: 'name 3',
          description: 'description 3',
          targetDate: '2025-03-01T19:55:14.217Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 93,
        },
        {
          name: 'name 4',
          description: 'description 4',
          targetDate: '2023-09-14T18:12:23.240Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 94,
        },
        {
          name: 'name 5',
          description: 'description 5',
          targetDate: '2024-03-24T02:40:16.086Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 67,
        },
      ],
      emissionSources: [
        {
          sourceType: 'sourceType 1',
          quantityUsed: 0.6,
          emissionFactors: 0.48,
          totalEmissions: 0.44,
          id: 8,
        },
        {
          sourceType: 'sourceType 2',
          quantityUsed: 0.14,
          emissionFactors: 0.77,
          totalEmissions: 0.81,
          id: 99,
        },
        {
          sourceType: 'sourceType 3',
          quantityUsed: 0.4,
          emissionFactors: 0.78,
          totalEmissions: 0.67,
          id: 81,
        },
        {
          sourceType: 'sourceType 4',
          quantityUsed: 0.77,
          emissionFactors: 0.72,
          totalEmissions: 0.17,
          id: 57,
        },
        {
          sourceType: 'sourceType 5',
          quantityUsed: 0.75,
          emissionFactors: 0.58,
          totalEmissions: 0.52,
          id: 19,
        },
      ],
      resourceUsage: [
        {
          resourceType: 'resourceType 1',
          quantityConsumed: 0.92,
          unitOfMeasurement: 'unitOfMeasurement 1',
          periodOfConsumption: '2024-11-20T22:21:01.118Z',
          id: 53,
        },
        {
          resourceType: 'resourceType 2',
          quantityConsumed: 0.29,
          unitOfMeasurement: 'unitOfMeasurement 2',
          periodOfConsumption: '2025-04-16T09:20:39.089Z',
          id: 77,
        },
        {
          resourceType: 'resourceType 3',
          quantityConsumed: 0.8,
          unitOfMeasurement: 'unitOfMeasurement 3',
          periodOfConsumption: '2025-03-05T21:41:21.257Z',
          id: 71,
        },
        {
          resourceType: 'resourceType 4',
          quantityConsumed: 0.63,
          unitOfMeasurement: 'unitOfMeasurement 4',
          periodOfConsumption: '2024-02-28T18:09:11.748Z',
          id: 77,
        },
        {
          resourceType: 'resourceType 5',
          quantityConsumed: 0.22,
          unitOfMeasurement: 'unitOfMeasurement 5',
          periodOfConsumption: '2023-07-11T23:04:10.631Z',
          id: 1,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('departmentsEntity', data.departments);
      await this.SeedResource('initiativesEntity', data.initiatives);
      await this.SeedResource('goalsEntity', data.goals);
      await this.SeedResource('emissionSourcesEntity', data.emissionSources);
      await this.SeedResource('resourceUsageEntity', data.resourceUsage);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
